theme: jekyll-theme-minimal
title: Linjie(Ethan) Xu
description:
personal_interest: 
logo: /assets/img/header.jpg
contact:
  email: linjiexuncu[at]outlook.com
  linkedin: https://www.linkedin.com/in/linjie-ethan-xu-700406138/
  github: https://github.com/egg-west
  resume: /assets/file/LinjieXuResume2022Spring.pdf
theme: jekyll-theme-minimal
google_analytics: G-C0SWW7WLTQ
