theme: jekyll-theme-minimal
title: Ruihan Yang
description: 杨睿涵 | ML, RL
personal_interest: 
logo: /assets/img/header.jpg
contact:
  email: ruihanyang97@gmail.com
  linkedin: https://www.linkedin.com/in/ruihan-yang-50102513b/
  github: https://github.com/RchalYang
  resume: /assets/file/RuihanYangResume2020Spring.pdf
theme: jekyll-theme-minimal
google_analytics: UA-155300005-1